apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: faang

resources:
  - ../base
  - ../../../components/dependencies/postgresql/internal
  - ../../../components/dependencies/redis/internal
  - ../../../components/dependencies/elasticsearch/internal
  - ../../../components/dependencies/kafka/internal
  - ../../../components/dependencies/minio/internal
