apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: faang

resources:
  - ../base
  - ../../../components/dependencies/postgresql/external
  - ../../../components/dependencies/redis/external
  - ../../../components/dependencies/elasticsearch/external
  - ../../../components/dependencies/kafka/external
  - ../../../components/dependencies/minio/internal
