apiVersion: v1
kind: ConfigMap
metadata:
  name: faang-config
data:
  POSTGRES_HOST: "postgres-main"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "faang"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-main:9092"
  REDIS_HOST: "redis-main"
  REDIS_PORT: "6379"
  ELASTICSEARCH_URL: "https://elasticsearch-main:9200"
  ELASTICSEARCH_TLS_INSECURE: "false"
  S3_ENDPOINT: "http://s3-main:9000"
  S3_BUCKET_NAME: "example-bucket"
  S3_AVATAR_BUCKET_NAME: "example-avatars"
  S3_REGION: "us-east-1"
  S3_DOWNLOAD_PATH: "/api/v1/buckets/example-bucket/objects/download?preview=true&prefix="
