apiVersion: v1
kind: Service
metadata:
  name: redis-main
  namespace: faang
  labels:
    app.kubernetes.io/part-of: faang-dependencies
    faang.io/dependency: redis
    faang.io/dependency-mode: internal
  annotations:
    argocd.argoproj.io/sync-wave: "-49"
spec:
  selector:
    faang.io/dependency: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
