apiVersion: v1
kind: ServiceAccount
metadata:
  name: faang-external-preflight
  labels:
    app.kubernetes.io/name: faang-external-preflight
    app.kubernetes.io/component: preflight
automountServiceAccountToken: false
