apiVersion: v1
kind: Secret
metadata:
  name: faang-secrets
  namespace: default
type: Opaque
stringData:
  # DB Credentials
  POSTGRES_USER: "your-postgres-user"
  POSTGRES_PASSWORD: "your-postgres-password"
  
  # Storage Credentials
  MINIO_ACCESS_KEY: "your-minio-access-key"
  MINIO_SECRET_KEY: "your-minio-secret-key"
  
  # External APIs
  SMTP_USERNAME: "your-email@gmail.com"
  SMTP_PASSWORD: "your-app-password"
  VONAGE_API_KEY: "your-vonage-key"
  VONAGE_API_SECRET: "your-vonage-secret"
  TELEGRAM_BOT_TOKEN: "your-telegram-token"
  
  # Security
  JWT_SECRET: "your-jwt-secret-key"

