apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: faang-dependencies
    faang.io/dependency: elasticsearch
    faang.io/dependency-mode: internal
  annotations:
    argocd.argoproj.io/sync-wave: "-49"

configMapGenerator:
  - name: faang-dependency-elasticsearch-selection
    namespace: faang
    literals:
      - mode=internal
