namespace: faang

resources:
  - namespace.yaml
  - ../../base
  - ../../bootstrap
  - ../../components/dependencies/postgresql/external
  - ../../components/dependencies/redis/external
  - ../../components/dependencies/elasticsearch/external
  - ../../components/dependencies/kafka/external
  - ../../components/dependencies/s3/internal

patches:
  - path: configmap.yaml
    target:
      kind: ConfigMap
      name: faang-config
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: faang-ingress

images:
  - name: docker-registry:5000/faang-account-service
    digest: sha256:875fae57a5a239286a3eb7b229d439c737657cda5548630b764d10e4df8e71c8
  - name: docker-registry:5000/faang-achievement-service
    digest: sha256:f2645cfc1a7c6bfc17716f9d8382ceda12922ff998e9a5c81f4b0cc382a51863
  - name: docker-registry:5000/faang-analytics-service
    digest: sha256:ad96fc11e0c99515cfaa90f35ac9885fbf8b5204df1166c7efb24e41d2095599
  - name: docker-registry:5000/faang-notification-service
    digest: sha256:e53a2070f8d9c137380b9dff4da871d31d02ca56ffbb599424308bb9e5df5235
  - name: docker-registry:5000/faang-payment-service
    digest: sha256:901be12b0fd000c00c92cd8628c8241b9e7dd7045d7193a8e7194b1387d006c3
  - name: docker-registry:5000/faang-post-service
    digest: sha256:fd40ebe8669431834e55d1cb58f84e3f4a846402063116083369a90a0bf6958e
  - name: docker-registry:5000/faang-project-service
    digest: sha256:c9363cf1eac36ae2fff438451d7f748a3def32d7bf3c0df6605ab67ad015961f
  - name: docker-registry:5000/faang-url-shortener-service
    digest: sha256:7712f923c06687c6298272299c50e36d0ba8ba37a72c8572bbb702a2d78d48c3
  - name: docker-registry:5000/faang-user-service
    digest: sha256:5fadb64932b29088ce4f8e9b5fad12944ef9857d42f06f97ec477e6f99ffd5a4
