apiVersion: v1
kind: Service
metadata:
  name: s3-main
  namespace: faang
  labels:
    app.kubernetes.io/part-of: faang-dependencies
    faang.io/dependency: s3
    faang.io/dependency-mode: external
  annotations:
    argocd.argoproj.io/sync-wave: "-49"
spec:
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      protocol: TCP
