apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: faang-gradle-cache
  namespace: jenkins
  labels:
    app.kubernetes.io/name: faang-build-agent-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: faang-grype-db-cache
  namespace: jenkins
  labels:
    app.kubernetes.io/name: faang-build-agent-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
