apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-management-tls
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: faang-private-tls
  source:
    repoURL: 'https://github.com/bormoley1983/faang-infra-env-homelab.git'
    targetRevision: main
    path: overlays/jenkins
    plugin:
      name: ksops-v1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
