apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - runtime-foundation-project.yaml
  - runtime-foundation-application.yaml
  - selected-dependencies-project.yaml
  - selected-dependencies-application.yaml
  - bootstrap-project.yaml
  - bootstrap-application.yaml
  - private-tls-project.yaml
  - faang-ingress-tls-application.yaml
  - argocd-management-tls-application.yaml
  - jenkins-management-tls-application.yaml
  - workloads-project.yaml
  - workloads-application.yaml
