apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: faang-private-tls
  namespace: argocd
spec:
  description: Private SOPS-encrypted TLS Secret delivery boundary
  sourceRepos:
    - 'https://github.com/bormoley1983/faang-infra-env-homelab.git'
  destinations:
    - namespace: faang
      server: 'https://kubernetes.default.svc'
    - namespace: argocd
      server: 'https://kubernetes.default.svc'
    - namespace: jenkins
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: ''
      kind: Secret
  orphanedResources:
    warn: true
