apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: faang-runtime-foundation
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: faang-runtime-foundation
  source:
    repoURL: 'https://github.com/bormoley1983/faang-infra-env-homelab.git'
    targetRevision: main
    path: overlays/runtime-foundation
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: faang
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
