apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: faang-workloads
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: faang-workloads
  source:
    repoURL: 'https://github.com/bormoley1983/faang-infra.git'
    targetRevision: refs/heads/dev-local
    path: k8s/overlays/homelab/boundaries/workloads
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: faang
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
