apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: faang
resources:
  - resources/ingress.yaml
  - resources/account-service.yaml
  - resources/achievement-service.yaml
  - resources/analytics-service.yaml
  - resources/notification-service.yaml
  - resources/payment-service.yaml
  - resources/post-service.yaml
  - resources/project-service.yaml
  - resources/url-shortener-service.yaml
  - resources/user-service.yaml
patches:
  - path: application-deployment-defaults.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: faang-.*-service
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: faang-ingress
images:
  - name: docker-registry:5000/faang-account-service
    digest: sha256:63e89d8352498825349c929fc20235fc582d81e8a3da353fbbf608c3c2d172e2
  - name: docker-registry:5000/faang-achievement-service
    digest: sha256:f2645cfc1a7c6bfc17716f9d8382ceda12922ff998e9a5c81f4b0cc382a51863
  - name: docker-registry:5000/faang-analytics-service
    digest: sha256:ad96fc11e0c99515cfaa90f35ac9885fbf8b5204df1166c7efb24e41d2095599
  - name: docker-registry:5000/faang-notification-service
    digest: sha256:e53a2070f8d9c137380b9dff4da871d31d02ca56ffbb599424308bb9e5df5235
  - name: docker-registry:5000/faang-payment-service
    digest: sha256:901be12b0fd000c00c92cd8628c8241b9e7dd7045d7193a8e7194b1387d006c3
  - name: docker-registry:5000/faang-post-service
    digest: sha256:0a44d9e08d895008fa26189b269d3e136564eb8640f85731520a8950785d2238
  - name: docker-registry:5000/faang-project-service
    digest: sha256:764049a25a74e68e98be58e34984a00b91c148725a269dd91b7069a5db034222
  - name: docker-registry:5000/faang-url-shortener-service
    digest: sha256:7712f923c06687c6298272299c50e36d0ba8ba37a72c8572bbb702a2d78d48c3
  - name: docker-registry:5000/faang-user-service
    digest: sha256:8bf1c466c53bdabf83f59375533593713cd958243681b44aa0be15143d3612b1
