apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: faang
resources:
  - resources/ingress.yaml
  - resources/application-metrics-network-policy.yaml
  - resources/account-service.yaml
  - resources/achievement-service.yaml
  - resources/analytics-service.yaml
  - resources/notification-service.yaml
  - resources/payment-service.yaml
  - resources/post-service.yaml
  - resources/project-service.yaml
  - resources/url-shortener-service.yaml
  - resources/user-service.yaml
patches:
  - path: application-deployment-defaults.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: faang-.*-service
  - path: application-service-metrics.yaml
    target:
      version: v1
      kind: Service
      name: faang-.*-service
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: faang-ingress
images:
  - name: docker-registry:5000/faang-account-service
    digest: sha256:28d1d93ac2ac1c00e6224a736ebf0f2fb46db797d7837107a97b190785fef8b7
  - name: docker-registry:5000/faang-achievement-service
    digest: sha256:b28988f2ed1c34b0ed02dac79ba8e72f7074f4500bcc580bab0423031673e017
  - name: docker-registry:5000/faang-analytics-service
    digest: sha256:c3145b635ffdd2d7577efee6cb6b49b19cc996e0d22a23b6442b7224c4602f7c
  - name: docker-registry:5000/faang-notification-service
    digest: sha256:791dcf7d507d291303ed836d4ad8bac552d196eed5acb1ebf8aaf0d1e64287ea
  - name: docker-registry:5000/faang-payment-service
    digest: sha256:96a7fa4c934ea28ed9c3fb4027006d167af118807c196f7a5ae2449412168049
  - name: docker-registry:5000/faang-post-service
    digest: sha256:4ef4bc23bb3fe57a90dd257d5390470ac1d66061f3f57dff345e90d596249f09
  - name: docker-registry:5000/faang-project-service
    digest: sha256:894187953d168f35409543986ef6940289e8725f07783971ecb92e654b0b462c
  - name: docker-registry:5000/faang-url-shortener-service
    digest: sha256:e1ad753e4c7a9ddc41c8b51ae7cc1e09270cae0207ab1b928e7e63d6a85a2f18
  - name: docker-registry:5000/faang-user-service
    digest: sha256:fc3df9a4d0b77f760853c388cb2c8774fb0c52ebe8fcb3fd1c9f8e02aa7df4bd
