apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: faang-system
  namespace: argocd
spec:
  project: faang
  source:
    repoURL: 'https://github.com/bormoley1983/faang-infra.git'
    targetRevision: dev-local
    path: k8s/overlays/homelab
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: faang
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
