apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: faang-kafka-canary
  namespace: argocd
spec:
  project: faang-kafka
  sources:
    - repoURL: 'quay.io/strimzi-helm'
      chart: strimzi-kafka-operator
      targetRevision: 1.2.0
      helm:
        releaseName: strimzi
        valueFiles:
          - $values/ops/kafka/operator-values.yaml
    - repoURL: 'https://github.com/bormoley1983/faang-infra.git'
      targetRevision: refs/heads/dev-local
      path: ops/kafka/manifests
    - repoURL: 'https://github.com/bormoley1983/faang-infra.git'
      targetRevision: refs/heads/dev-local
      path: ops/kafka/canary
    - repoURL: 'https://github.com/bormoley1983/faang-infra.git'
      targetRevision: refs/heads/dev-local
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: faang-kafka-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
