apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project.yaml
  - application.yaml
  - storage-project.yaml
  - storage-application.yaml
  - postgresql-project.yaml
  - postgresql-operator-application.yaml
  - postgresql-canary-foundation-application.yaml
  - postgresql-canary-application.yaml
