apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: faang-monitoring-secrets
  namespace: argocd
spec:
  project: faang-monitoring-secrets
  source:
    repoURL: 'https://github.com/bormoley1983/faang-infra-env-homelab.git'
    targetRevision: main
    path: overlays/monitoring
    plugin:
      name: ksops-v1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
