apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: faang-storage
  namespace: argocd
spec:
  project: faang-storage
  sources:
    - repoURL: 'https://charts.longhorn.io'
      chart: longhorn
      targetRevision: 1.12.1
      helm:
        releaseName: longhorn
        valueFiles:
          - $values/ops/storage/longhorn/values.yaml
    - repoURL: 'https://github.com/bormoley1983/faang-infra.git'
      targetRevision: refs/heads/dev-local
      path: ops/storage/longhorn/manifests
    - repoURL: 'https://github.com/bormoley1983/faang-infra.git'
      targetRevision: refs/heads/dev-local
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn-system
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: longhorn-default-resource
      namespace: longhorn-system
      jsonPointers:
        - /data/default-resource.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
