apiVersion: v1
kind: Secret
metadata:
  name: strimzi-oci-helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: strimzi-oci-helm
  url: quay.io/strimzi-helm
  enableOCI: "true"
