resources:
  - configmap.yaml
  - secret.yaml
  - ingress.yaml
  - account-service.yaml
  - achievement-service.yaml
  - analytics-service.yaml
  - notification-service.yaml
  - payment-service.yaml
  - post-service.yaml
  - project-service.yaml
  - url-shortener-service.yaml
